apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 32001  # NodePort range: 30000-32767
  selector:
    app: db
