apiVersion: batch/v1
kind: Job
metadata:
  name: write-to-pv-job
spec:
  template:
    spec:
      containers:
      - name: write-container
        image: busybox
        command: ["sh", "-c", "echo 'Hello le monde' >> /data/file.txt"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc
  backoffLimit: 4
